name = "pulse-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
APP_URL = "https://pulse.inovacx.com"

[[d1_databases]]
binding = "DB"
database_name = "pulse-db"
database_id = "db7e5a8c-6845-46e9-bb44-9b6f2d2885dc"

[[kv_namespaces]]
binding = "SESSIONS"
id = "ed7a3e9dcfc14ea89d1b75bb08706416"
